version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.2

commands:
  prepare:
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y binutils-arm-linux-gnueabi binutils-arm-linux-gnueabihf binutils-mips64el-linux-gnuabi64 binutils-mipsel-linux-gnu
      - run:
          name: Fix the freetype stuff, idek
          command:  |
            if [ -d out/sysroot-build/bullseye/debian-packages]; then
              rm out/sysroot-build/bullseye/debian-packages/libfreetype6*
            fi
  build-image:
    parameters:
      image:
        type: string
    steps:
      - prepare
      - run:
          name: Build sysroot
          command: |
            ./build/linux/sysroot_scripts/sysroot-creator-bullseye.sh << parameters.image >>
      - persist_to_workspace:
          root: .
          paths:
            - out/sysroot-build/bullseye/*.tar.xz

jobs:
  build:
    parameters:
      image:
        type: string
    docker:
      - image: cimg/python:3.10.4
    resource_class: 2xlarge
    steps:
      - build-image:
          image: << parameters.image >>
  upload-images:
    docker:
      - image: cimg/base:2022.04
    resource_class: large
    steps:
      - prepare
      - azure-cli/install
      - attach_workspace:
          at: .
      - run:
          name: Upload Sysroots
          command: SKIP_SYSROOT_BUILD=true ./build/linux/sysroot_scripts/build_and_upload.py
      - store_artifacts:
          path: build/linux/sysroot_scripts/sysroots.json
          destination: sysroots.json

workflows:
  version: 2.1
  build-and-upload:
    jobs:
      - build:
          image: BuildSysrootARM64
          name: build-image-arm64
      - build:
          image: BuildSysrootMips64el
          name: build-image-mips64
      - build:
          image: BuildSysrootMips
          name: build-image-mips
      - build:
          image: BuildSysrootARMEL
          name: build-image-armel
      - build:
          image: BuildSysrootARM
          name: build-image-arm
      - build:
          image: BuildSysrootAmd64
          name: build-image-x64
      - build:
          image: BuildSysrootI386
          name: build-image-i386
      - upload-images:
          requires:
            - build-image-arm64
            - build-image-mips64
            - build-image-mips
            - build-image-armel
            - build-image-arm
            - build-image-x64
            - build-image-i386
